PackageCode/objects/US_Account_Target_Program__c.object
<CustomObject>
    <fields>
        <fullName>WSLR_Target_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WSLR Target Program</label>
        <referenceTo>WSLR_Target_Program__c</referenceTo>
        <relationshipLabel>Account Target Programs</relationshipLabel>
        <relationshipName>Account_Target_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

retrieveUnpackaged/objects/US_Account_Target_Program__c.object
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Target Programs</relationshipLabel>
        <relationshipName>Account_Target_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>

retrieveUnpackaged/objects/US_Account_Target_Program__c.object
    <fields>
        <fullName>Brand_Category__c</fullName>
        <label>Brand Category</label>
        <length>40</length>
        <type>Text</type>
    </fields>

retrieveUnpackaged/objects/US_Account_Target_Program__c.object
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <length>40</length>
        <type>Text</type>
    </fields>

ProjectCode08272016/objects/US_Account_Target_Program__c.object
    <fields>
        <fullName>Wholesaler_Number__c</fullName>
        <formula>Account__r.WSLR_NBR_US__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Wholesaler Number</label>
        <type>Text</type>
    </fields>

PackageCode/objects/WSLR_Target_Program__c.object
<CustomObject>
    <description>US object for SAP Targets at WSLR Level</description>
    <fields>
        <fullName>Brand_Category__c</fullName>
        <label>Brand Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wholesaler__c</fullName>
        <inlineHelpText>To which wholesaler is this target program applied?</inlineHelpText>
        <label>Wholesaler</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>WSLR Target Programs</relationshipLabel>
        <relationshipName>WSLR_Target_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>WSLR Target Program</label>
    <nameField>
        <displayFormat>WTP-{00000}</displayFormat>
        <label>WSLR Target Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WSLR Target Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PackageCode/classes/ABS_Batch_WTP_Populate.cls
global class ABS_Batch_WTP_Populate implements database.Batchable<sobject>{

    /***
    Start method for Querying all the opportunities and return to execute method
    ***/


    public ABS_Batch_WTP_Populate (){

    }

    global database.Querylocator start(database.batchablecontext bc){
      
        string squery ='select id, Account__c, Account__r.Wholesaler__r.id, Brand_Category__c, Channel__c, Wholesaler_Number__c, WSLR_Target_Program__c';
        squery+=' from US_Account_Target_Program__c WHERE WSLR_Target_Program__c  = null order by Account__r.Wholesaler__r.id'; 

        
       if(Test.isRunningTest())
         squery= squery+ ' LIMIT 10';   
       //else
         //squery= squery + ' LIMIT 100';   

     
       system.debug('squery = ' + squery);
        return database.getQuerylocator(squery);
    }


    //Execute method to process all 
    global void execute(database.batchablecontext bc,list<US_Account_Target_Program__c> lstATPs){
        system.debug('lstATPs.size() = ' + lstATPs.size());
        set<id> setWslrs = new set<id>();
        for(US_Account_Target_Program__c iP :lstATPs){
            system.debug('iP.Account__r.Wholesaler__c = ' + iP.Account__r.Wholesaler__c);
            setWslrs.add(iP.Account__r.Wholesaler__c);
        }
        //get the wslr targets for these wslrs
        list<WSLR_Target_Program__c> lstWTPs =[SELECT id, Wholesaler__r.id,Brand_Category__c, Channel__c from WSLR_Target_Program__c where Wholesaler__c in :setWslrs]; 

        //boolean bFound = false;
        for(US_Account_Target_Program__c iATP :lstATPs){
            //bFound = false;
            system.debug('ATP');
            for(WSLR_Target_Program__c iWTP :lstWTPs ){
                system.debug('WTP');
                String BCtranslate = iWTP.Brand_Category__c;
                if(iWTP.Channel__c == 'ONP' && iWTP.Brand_Category__c == 'CORE'){
                    BCtranslate = 'DRFT';
                }
                if (iWTP.Wholesaler__r.id == iATP.Account__r.Wholesaler__r.id &&  BCtranslate == iATP.Brand_Category__c && iWTP.Channel__c== iATP.Channel__c ){
                    iATP.WSLR_Target_Program__c = iWTP.id;
                    system.debug('WTP FOUND');
                    Break;                
                }
            }
        }

        system.debug('update lstATPs');
        update lstATPs;
    }
    
    global void finish(database.batchablecontext bc){}
    
}